export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const ACCOUNT_CONFIRMATION = 'ACCOUNT_CONFIRMATION';
export const ACCOUNT_CONFIRMATION_SUCCESS = 'ACCOUNT_CONFIRMATION_SUCCESS';
export const ACCOUNT_CONFIRMATION_ERROR = 'ACCOUNT_CONFIRMATION_ERROR';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';

export const COURSES_REQUEST = 'COURSES_REQUEST';
export const COURSES_SUCCESS = 'COURSES_SUCCESS';
export const COURSES_ERROR = 'COURSES_ERROR';

