export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const ACCOUNT_CONFIRMATION = 'ACCOUNT_CONFIRMATION';
export const ACCOUNT_CONFIRMATION_SUCCESS = 'ACCOUNT_CONFIRMATION_SUCCESS';
export const ACCOUNT_CONFIRMATION_ERROR = 'ACCOUNT_CONFIRMATION_ERROR';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';

export const COURSES_REQUEST = 'COURSES_REQUEST';
export const COURSES_SUCCESS = 'COURSES_SUCCESS';
export const COURSES_ERROR = 'COURSES_ERROR';

export const COURSES_BY_CATEGORY_REQUEST = 'COURSES_BY_CATEGORY_REQUEST';
export const COURSES_BY_CATEGORY_SUCCESS = 'COURSES_BY_CATEGORY_SUCCESS';
export const COURSES_BY_CATEGORY_ERROR = 'COURSES_BY_CATEGORY_ERROR';

export const COURSE_REQUEST = 'COURSE_REQUEST';
export const COURSE_SUCCESS = 'COURSE_SUCCESS';
export const COURSE_ERROR = 'COURSE_ERROR';

export const SEARCH_COURSES_REQUEST = 'SEARCH_COURSES_REQUEST';
export const SEARCH_COURSES_SUCCESS = 'SEARCH_COURSES_SUCCESS';
export const SEARCH_COURSES_ERROR = 'SEARCH_COURSES_ERROR';

export const INSTR_COURSES_REQUEST = 'INSTR_COURSES_REQUEST';
export const INSTR_COURSE_REQUEST = 'INSTR_COURSE_REQUEST';
export const INSTR_COURSES_SUCCESS = 'INSTR_COURSES_SUCCESS';
export const INSTR_COURSES_ERROR = 'INSTR_COURSES_ERROR';
export const INSTR_COURSE_SUCCESS = 'INSTR_COURSE_SUCCESS';

export const INSTR_COURSE_CREATE_REQUEST = 'INSTR_COURSE_CREATE_REQUEST';
export const INSTR_COURSE_CREATE_SUCCESS = 'INSTR_COURSE_CREATE_SUCCESS';
export const INSTR_COURSE_CREATE_ERROR = 'INSTR_COURSE_CREATE_ERROR';

export const INSTR_COURSE_UPDATE_REQUEST = 'INSTR_COURSE_UPDATE_REQUEST';
export const INSTR_COURSE_UPDATE_SUCCESS = 'INSTR_COURSE_UPDATE_SUCCESS';
export const INSTR_COURSE_UPDATE_ERROR = 'INSTR_COURSE_UPDATE_ERROR';

export const INSTR_COURSE_TARGET_REQUEST = 'INSTR_COURSE_TARGET_REQUEST';
export const INSTR_COURSE_TARGET_SUCCESS = 'INSTR_COURSE_TARGET_SUCCESS';
export const INSTR_COURSE_TARGET_ERROR = 'INSTR_COURSE_TARGET_ERROR';

export const INSTR_CREATE_COURSE_TARGET_REQUEST = 'INSTR_CREATE_COURSE_TARGET_REQUEST';
export const INSTR_CREATE_COURSE_TARGET_SUCCESS = 'INSTR_CREATE_COURSE_TARGET_SUCCESS';
export const INSTR_CREATE_COURSE_TARGET_ERROR = 'INSTR_CREATE_COURSE_TARGET_ERROR';

export const INSTR_DELETE_COURSE_REQ_GOAL_REQUEST = 'INSTR_DELETE_COURSE_REQ_GOAL_REQUEST';
export const INSTR_DELETE_COURSE_REQ_GOAL_SUCCESS = 'INSTR_DELETE_COURSE_REQ_GOAL_SUCCESS';
export const INSTR_DELETE_COURSE_REQ_GOAL_ERROR = 'INSTR_DELETE_COURSE_REQ_GOAL_ERROR';

export const INSTR_STUDENTS_REQUEST = 'INSTR_STUDENTS_REQUEST';
export const INSTR_STUDENTS_SUCCESS = 'INSTR_STUDENTS_SUCCESS';
export const INSTR_STUDENTS_ERROR = 'INSTR_STUDENTS_ERROR';

export const CART_COURSES_REQUEST = 'CART_COURSES_REQUEST';
export const CART_COURSES_SUCCESS = 'CART_COURSES_SUCCESS';
export const CART_COURSES_ERROR = 'CART_COURSES_ERROR';

export const ADD_COURSE_TO_CART_REQUEST = 'ADD_COURSE_TO_CART_REQUEST';
export const ADD_COURSE_TO_CART_SUCCESS = 'ADD_COURSE_TO_CART_SUCCESS';
export const ADD_COURSE_TO_CART_ERROR = 'ADD_COURSE_TO_CART_ERROR';

export const DELETE_COURSE_FROM_CART_REQUEST = 'DELETE_COURSE_FROM_CART_REQUEST';
export const DELETE_COURSE_FROM_CART_SUCCESS = 'DELETE_COURSE_FROM_CART_SUCCESS';
export const DELETE_COURSE_FROM_CART_ERROR = 'DELETE_COURSE_FROM_CART_ERROR';

export const EMPTY_CART_REQUEST = 'EMPTY_CART_REQUEST';
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';
export const EMPTY_CART_ERROR = 'EMPTY_CART_ERROR';

export const REGISTER_TO_COURSE_REQUEST = 'REGISTER_TO_COURSE_REQUEST';
export const REGISTER_TO_COURSE_SUCCESS = 'REGISTER_TO_COURSE_SUCCESS';
export const REGISTER_TO_COURSE_ERROR = 'REGISTER_TO_COURSE_ERROR';

export const MY_COURSES_REQUEST = 'MY_COURSES_REQUEST';
export const MY_COURSES_SUCCESS = 'MY_COURSES_SUCCESS';
export const MY_COURSES_ERROR = 'MY_COURSES_ERROR';

export const ADD_COURSE_SECTION_REQUEST = 'ADD_COURSE_SECTION_REQUEST';
export const ADD_COURSE_SECTION_SUCCESS = 'ADD_COURSE_SECTION_SUCCESS';
export const ADD_COURSE_SECTION_ERROR = 'MY_COURSES_ERROR';

export const EDIT_COURSE_SECTION_REQUEST = 'EDIT_COURSE_SECTION_REQUEST';
export const EDIT_COURSE_SECTION_SUCCESS = 'EDIT_COURSE_SECTION_SUCCESS';
export const EDIT_COURSE_SECTION_ERROR = 'EDIT_COURSE_SECTION_ERROR';

export const DELETE_COURSE_SECTION_REQUEST = 'DELETE_COURSE_SECTION_REQUEST';
export const DELETE_COURSE_SECTION_SUCCESS = 'DELETE_COURSE_SECTION_SUCCESS';
export const DELETE_COURSE_SECTION_ERROR = 'DELETE_COURSE_SECTION_ERROR';

export const ADD_COURSE_LECTURE_REQUEST = 'ADD_COURSE_LECTURE_REQUEST';
export const ADD_COURSE_LECTURE_SUCCESS = 'ADD_COURSE_LECTURE_SUCCESS';
export const ADD_COURSE_LECTURE_ERROR = 'ADD_COURSE_LECTURE_ERROR';

export const EDIT_COURSE_LECTURE_REQUEST = 'EDIT_COURSE_LECTURE_REQUEST';
export const EDIT_COURSE_LECTURE_SUCCESS = 'EDIT_COURSE_LECTURE_SUCCESS';
export const EDIT_COURSE_LECTURE_ERROR = 'EDIT_COURSE_LECTURE_ERROR';

export const DELETE_COURSE_LECTURE_REQUEST = 'DELETE_COURSE_LECTURE_REQUEST';
export const DELETE_COURSE_LECTURE_SUCCESS = 'DELETE_COURSE_LECTURE_SUCCESS';
export const DELETE_COURSE_LECTURE_ERROR = 'DELETE_COURSE_LECTURE_ERROR';

