export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const ACCOUNT_CONFIRMATION = 'ACCOUNT_CONFIRMATION';
export const ACCOUNT_CONFIRMATION_SUCCESS = 'ACCOUNT_CONFIRMATION_SUCCESS';
export const ACCOUNT_CONFIRMATION_ERROR = 'ACCOUNT_CONFIRMATION_ERROR';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';

export const COURSES_REQUEST = 'COURSES_REQUEST';
export const COURSES_SUCCESS = 'COURSES_SUCCESS';
export const COURSES_ERROR = 'COURSES_ERROR';

export const COURSE_REQUEST = 'COURSE_REQUEST';
export const COURSE_SUCCESS = 'COURSE_SUCCESS';
export const COURSE_ERROR = 'COURSE_ERROR';

export const INSTR_COURSES_REQUEST = 'INSTR_COURSES_REQUEST';
export const INSTR_COURSE_REQUEST = 'INSTR_COURSE_REQUEST';
export const INSTR_COURSES_SUCCESS = 'INSTR_COURSES_SUCCESS';
export const INSTR_COURSES_ERROR = 'INSTR_COURSES_ERROR';
export const INSTR_COURSE_SUCCESS = 'INSTR_COURSE_SUCCESS';

export const INSTR_COURSE_CREATE_REQUEST = 'INSTR_COURSE_CREATE_REQUEST';
export const INSTR_COURSE_CREATE_SUCCESS = 'INSTR_COURSE_CREATE_SUCCESS';
export const INSTR_COURSE_CREATE_ERROR = 'INSTR_COURSE_CREATE_ERROR';

export const INSTR_COURSE_UPDATE_REQUEST = 'INSTR_COURSE_UPDATE_REQUEST';
export const INSTR_COURSE_UPDATE_SUCCESS = 'INSTR_COURSE_UPDATE_SUCCESS';
export const INSTR_COURSE_UPDATE_ERROR = 'INSTR_COURSE_UPDATE_ERROR';

export const INSTR_COURSE_TARGET_REQUEST = 'INSTR_COURSE_TARGET_REQUEST';
export const INSTR_COURSE_TARGET_SUCCESS = 'INSTR_COURSE_TARGET_SUCCESS';
export const INSTR_COURSE_TARGET_ERROR = 'INSTR_COURSE_TARGET_ERROR';

export const INSTR_CREATE_COURSE_TARGET_REQUEST = 'INSTR_CREATE_COURSE_TARGET_REQUEST';
export const INSTR_CREATE_COURSE_TARGET_SUCCESS = 'INSTR_CREATE_COURSE_TARGET_SUCCESS';
export const INSTR_CREATE_COURSE_TARGET_ERROR = 'INSTR_CREATE_COURSE_TARGET_ERROR';

export const INSTR_DELETE_COURSE_REQ_GOAL_REQUEST = 'INSTR_DELETE_COURSE_REQ_GOAL_REQUEST';
export const INSTR_DELETE_COURSE_REQ_GOAL_SUCCESS = 'INSTR_DELETE_COURSE_REQ_GOAL_SUCCESS';
export const INSTR_DELETE_COURSE_REQ_GOAL_ERROR = 'INSTR_DELETE_COURSE_REQ_GOAL_ERROR';

export const CART_COURSES_REQUEST = 'CART_COURSES_REQUEST';
export const CART_COURSES_SUCCESS = 'CART_COURSES_SUCCESS';
export const CART_COURSES_ERROR = 'CART_COURSES_ERROR';

export const ADD_COURSE_TO_CART_REQUEST = 'ADD_COURSE_TO_CART_REQUEST';
export const ADD_COURSE_TO_CART_SUCCESS = 'ADD_COURSE_TO_CART_SUCCESS';
export const ADD_COURSE_TO_CART_ERROR = 'ADD_COURSE_TO_CART_ERROR';
